### ISSUE TITLE
Error when starting PO3 3.3.56 server

### ISSUE THREAD

**Issue by yqyjyx** [Cazadorsniper/PO3#1055]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.3.56
**Pack Mode (Normal, Titan, Kappa):**Normal
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**NoClassDefFoundError, seemed to be caused by slimeknights and tinkers

**Steps to reproduce:**Try to boot up a server

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/bdkYfSyA

Edit:The tinkers' reforged jar file seems to be the problem. The jar file initially wasn't even in the mods folder for the server. However, adding the jar file then disabling it(I did it through a rename) seems to solve the problem

**Comment by nycolassoares** [comment]
same problem :(

**Comment by Splatgerty** [comment]
Having the same issue. No solution found yet :( I've tried doing a fresh install of the pack and the server to no avail.

**Comment by Cazadorsniper** [comment]
Ok

**Comment by Cazadorsniper** [comment]
For now disable Tinkers' Reforged.

**Comment by yqyjyx** [comment]
will disabling tinkers reforged break anything?

**Comment by Cazadorsniper** [comment]
Shouldn't

**Comment by yqyjyx** [comment]
sorry for being stupid but what exactly is the jar file for tinkers' reforged called?

**Comment by Cazadorsniper** [comment]
tinkers_reforged-1.0.6

**Comment by yqyjyx** [comment]
Weirdly enough, tinkers reforged isn't actually in the server's mods folder. However, adding it did not change the issue at all. The crash error is the exact same.

**Comment by Spoilerfx** [comment]
Disabling tinkers_reforged allowed me to start the server.

**Comment by yqyjyx** [comment]
That's odd, I'll keep testing

**Comment by Arsha72128** [comment]
Disabling tinkers_reforged did not work for me either.

**Comment by Frikkle** [comment]
For me, Tinkers' Reforged was inside the server's mod folder and disabling it did solve the issue described in the issue description.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/2947150 this build of tinkers' Reforged should fix the issue. have a nice day

**Comment by gorillastomp** [comment]
@Mrthomas20121 I used your updated file but it was still crashing the server.

**Comment by Caedis** [comment]
@Mrthomas20121 Different error now (yay progress): https://pastebin.com/RC8bvdkQ
Shall I create an issue on your repo as well?

**Comment by Caedis** [comment]
@Cazadorsniper Tinker's Reforged was updated with a fix that resolves this issue.
