### ISSUE TITLE
Metallurgic Quest not detecting

### ISSUE THREAD

**Issue by jmann18** [Cazadorsniper/PO3#320]
v3.0.39
Singleplayer

I have the metallurgic infuser in my inventory but the quest won't detect even when I click the detect/submit button.

I had the metallurgic infuser before the quest was available and then I just broke it and tried to claim the quest. When that didn't work I made a new one and the quest still won't detect.

**Comment by jmann18** [comment]
Fixed by restarting game.

**Comment by lauchlinmac** [comment]
I'm having the same issue, though it doesn't fix when I restart.
